# Secrets Manager -> k8s Secret sinxronizasiyasi
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: app
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-north-1        # <-- oz region-un
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: app
spec:
  refreshInterval: 1h             # parol rotasiya olunsa avtomatik yenilenir
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: db-credentials          # yaranacaq k8s Secret-in adi
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: my-springboot-eks/db-credentials   # <-- terraform output db_secret_name
        property: username
    - secretKey: password
      remoteRef:
        key: my-springboot-eks/db-credentials
        property: password
    - secretKey: jdbc_url
      remoteRef:
        key: my-springboot-eks/db-credentials
        property: jdbc_url
